---
# defaults file for ansible-role-nginx

# порт nginx
nginx_port: 80

# порт сервера, на который будут проксироваться запросы
nginx_proxy_port: 8000

# айпи сервера, на который будут проксироваться запросы
nginx_proxy_ip: localhost

# директория со статическими файлами
nginx_static_path: /var/html/static/

# пути для хранения кастомного конфига nginx
nginx_conf_src: nginx.conf.j2
nginx_conf_dest: /etc/nginx/conf.d/custom_nginx.conf