---

# tasks file for append users to docker group for ansible-role-docker

- name: Проверка, что группа "docker" существует
  ansible.builtin.group:
    name: docker
    state: present

- name: Проверяем необходимость добавляния пользователй в группу "docker"
  set_fact:
    at_least_one_user_to_append: true
  when:
    - docker_users is iterable
    - docker_users | length > 0
  with_items: "{{ docker_users }}"


- name: Добавляем пользоватей "docker_users" в группу "docker"
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
  when: at_least_one_user_to_append is defined
