---
# tasks file for nginx

# Установка Nginx
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  notify:
    - Restart Nginx

# Настройка Nginx
- name: Copy Nginx conf file
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Restart Nginx
