---
# tasks file for ansible-role-nginx

# Установка Nginx
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

# Запуск Nginx
- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

# Настройка Nginx
- name: Copy Nginx conf file
  ansible.builtin.template:
    src: "{{ nginx_conf_src }}"
    dest: "{{ nginx_conf_dest }}"
  notify:
    - Restart Nginx

# Удаление сайта default
- name: Delete Nginx default site
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify:
    - Restart Nginx