---

# tasks file for append users to docker group for ansible-role-docker

- name: Проверка, что группа "docker" существует
  ansible.builtin.group:
    name: docker
    state: present

- name: Добавляем пользоватей "docker_users" в группу "docker"
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
  when:
    - docker_users is iterable
    - docker_users | length > 0
